spring:
  profiles:
    active:
    -dev
---
spring:
  profiles: dev
  application:
    name: microservicecloud-config-zhangdian-dev
---
spring:
  profiles: test
  application:
    name: microservicecloud-config-zhangdian-test